services:
  ubuntu_arm64_builder:
    image: local/builder:ubuntu22-arm64
    platform: linux/arm64
    command: /bin/bash /startup/start.sh
    volumes:
      - in_progress:/in_progress
      - ${WORKING_DIR}/data:/startup
      - ${WORKING_DIR}/src:/todo
      - ${WORKING_DIR}/out:/complete

volumes:
  in_progress:
