services:
  windows_amd64_builder:
    image: local/builder:windows-cross
    command: /bin/bash /startup/start.sh
    volumes:
      - in_progress:/in_progress
      - ${WORKING_DIR}/data:/startup
      - ${WORKING_DIR}/src:/todo
      - ${WORKING_DIR}/out:/complete
      - windows_amd64_go_cache:/root/go/pkg/mod
      - windows_amd64_cargo_cache:/root/.cargo/registry

volumes:
  in_progress:
  windows_amd64_go_cache:
  windows_amd64_cargo_cache:
